homepage:
  url: /
  controller: IndexController
  function: Index
  method: GET

blog:
  url: user/create
  controller: IndexController
  function: UserCreate
  method: GET

user_login:
  url: user/login
  controller: IndexController
  function: Login
  method: GET

user_sign_in:
  url: user/logout
  controller: IndexController
  function: Logout
  method: GET

user_login_post:
  url: user/loginpost
  controller: IndexController
  function: UserLogin_Post
  method: POST

update:
  url: update
  controller: IndexController
  function: Update
  method: GET

